---

- hosts: all
  become: true
  pre_tasks:

  - include_vars: ./vars_ubuntu.yml
    when: ansible_distribution == "Ubuntu"

  - include_vars: ./vars_centos.yml
    when: ansible_distribution == "CentOS"

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

  - name: copy default html file for site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    package:
      name:
        - "{{ mariadb_package }}"
      state: latest

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
