---

- hosts: all
  become: true
  tasks:

  - include_vars: ./vars_ubuntu.yml
    when: ansible_distribution == "Ubuntu"

  - include_vars: ./vars_centos.yml
    when: ansible_distribution == "CentOS"

  - name: remove apache2 package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
