- name: install mariadb (Centos)
  tags: db,mariadb,centos
  package:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb (Ubuntu)
  tags: db,mariadb,ubuntu
  package:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
